### PR TITLE
Use Meta.lower to handle cases the same way base broadcasting does.

### PR DESCRIPTION
**Pull request by chriselrod**

### CODE REVIEW

**Comment by devmotion** [comment]
I guess it takes care of `begin` as well?

**Comment by chriselrod** [comment]
> I guess it takes care of `begin` as well?

Yes.
```julia
julia> @macroexpand @muladd @.. a = b + x[begin] * (0.2c[end] + 0.3d[3] + 0.4e[begin] + 0.5f[r] + 0.6g + 0.6h + 0.6i)
quote
    var"##fastbroadcast#404_1" = Base.firstindex(x)
    var"##fastbroadcast#404_2" = (Base.Broadcast.dotview)(x, var"##fastbroadcast#404_1")
    var"##fastbroadcast#404_3" = (Base.Broadcast.dotview)(f, r)
    var"##fastbroadcast#404_4" = Base.firstindex(e)
    var"##fastbroadcast#404_5" = (Base.Broadcast.dotview)(e, var"##fastbroadcast#404_4")
    var"##fastbroadcast#404_6" = (Base.Broadcast.dotview)(d, 3)
    var"##fastbroadcast#404_7" = Base.lastindex(c)
    var"##fastbroadcast#404_8" = (Base.Broadcast.dotview)(c, var"##fastbroadcast#404_7")
    var"##fastbroadcast#404_9" = Base.broadcasted(*, 0.2, var"##fastbroadcast#404_8")
    var"##fastbroadcast#404_10" = Base.broadcasted(muladd, 0.3, var"##fastbroadcast#404_6", var"##fastbroadcast#404_9")
    var"##fastbroadcast#404_11" = Base.broadcasted(muladd, 0.4, var"##fastbroadcast#404_5", var"##fastbroadcast#404_10")
    var"##fastbroadcast#404_12" = Base.broadcasted(muladd, 0.5, var"##fastbroadcast#404_3", var"##fastbroadcast#404_11")
    var"##fastbroadcast#404_13" = Base.broadcasted(muladd, 0.6, g, var"##fastbroadcast#404_12")
    var"##fastbroadcast#404_14" = Base.broadcasted(muladd, 0.6, h, var"##fastbroadcast#404_13")
    var"##fastbroadcast#404_15" = Base.broadcasted(muladd, 0.6, i, var"##fastbroadcast#404_14")
    var"##fastbroadcast#404_16" = Base.broadcasted(muladd, var"##fastbroadcast#404_2", var"##fastbroadcast#404_15", b)
    var"##fastbroadcast#404_17" = (FastBroadcast.fast_materialize!)(a, var"##fastbroadcast#404_16")
end
```

**Comment by devmotion** [comment]
Great!

**Comment by chriselrod** [comment]
Test failures are
a) 1.0 having defined internal types differently from 1.6 (many changes happened in the 1.6-DEV timeframe, but some earlier). I've now installed it locally.
b) Using `Meta.@lower` can introduce gotos, so I'll have to add handling.

**Comment by chriselrod** [comment]
After adding `goto` support and some checks for different versions, this PR is no longer less code than the old one.
Macro expansion time from this approach will also be slower.

`Expr` are probably more stable between Julia versions than things like `Core.GotoIfNot`, so long term this approach may introduce just as many issues.

So we should consider continuing on with the old approach and adding corner cases as they come.

**Comment by ChrisRackauckas** [comment]
Tests passed. Merge and pass?

**Pull request merged**
